version: '3'
services:
  androidapi:
    build: 
      context: .
      dockerfile: ./Services/AndroidApi/dockerfile
    ports:
      - "8080:8080"
    env_file:
      - otel/otel-dotnet.env # Enables OpenTelemetry .NET Automatic Instrumentation
    environment:
      # OpenTelemetry environmental variables:
      OTEL_SERVICE_NAME: "androidapi"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
    networks:
      - my-network
    depends_on:
      - otel-collector

  catalog:
    build: 
      context: .
      dockerfile: ./Services/Catalog/dockerfile
    ports:
      - "8081:8080"
    env_file:
      - otel/otel-dotnet.env # Enables OpenTelemetry .NET Automatic Instrumentation
    environment:
      # OpenTelemetry environmental variables:
      OTEL_SERVICE_NAME: "catalog"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
    networks:
      - my-network
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.78.0
    volumes:
      - ./otel/otel-config.yaml:/etc/otel/config.yaml
      - ./log:/log/otel
    command: --config /etc/otel/config.yaml
    environment:
      JAEGER_ENDPOINT: "jaeger:4317"
      LOKI_ENDPOINT: "http://loki:3100/loki/api/v1/push"
    ports:
      - "8889:8889"   # Prometheus metrics exporter (scrape endpoint)
      - "13133:13133" # health_check extension
      - "55679:55679" # ZPages extension
    depends_on:
      - jaeger
      - prometheus
      - loki
    networks:
      - my-network

  jaeger:
    image: jaegertracing/all-in-one:1.46.0
    ports:
      - "16686:16686" # Jaeger Web UI
    networks:
      - my-network

  prometheus:
    image: prom/prometheus:v2.42.0
    volumes:
      - ./otel/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - my-network

  loki:
    image: grafana/loki:2.7.4
    ports:
      - "3100:3100"
    networks:
      - my-network

  grafana:
    image: grafana/grafana:9.4.3
    volumes:
      - ./otel/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    ports:
      - "3000:3000"
    networks:
      - my-network

networks:
  my-network:
