version: '3'
services:
  androidapi:
    build: 
      context: .
      dockerfile: ./Services/AndroidApi/dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network
  catalog:
    build: 
      context: .
      dockerfile: ./Services/Catalog/dockerfile
    ports:
      - "8081:8080"
    networks:
      - my-network
networks:
  my-network: