name: Catalog service CI/CD
run-name: ${{ github.actor }} is building the catalog service 🚀

on: [
  workflow_dispatch
]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./Services/Catalog/dockerfile
          push: true
          tags: ghcr.io/tom171296/craftedspecially/catalog-service:latest

  deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: 'CraftedSpecially'
          cluster-name: 'aks'
      
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy to AKS
        id: deploy
        uses: Azure/K8s-deploy@v4
        with:
          namespace: 'default'
          manifests: |
            ./Services/Catalog/catalog-service.yml
  
  Release: 
    needs: deployment
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run release
        run: |
          echo "Running release..."

  Load-test: 
    needs: Deployment
    runs-on: ubuntu-latest
    environment: Continuous-validation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run load test
        run: |
          echo "Running load test..."
            
  Continuous-validation:
    needs: Load-test
    runs-on: ubuntu-latest
    environment: Continuous-validation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run load test
        run: |
          echo "Running load test..."

      - name: Run chaos experiment
        run: |
          echo "Running chaos test..."
