name: Deploy continuous validation

on:
    workflow_call

deploy-continuous-validation:
    runs-on: ubuntu-latest
    needs: setup-namespaces
    environment: Continuous-validation
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      id: set-context
      uses: azure/aks-set-context@v3
      with:
        resource-group: 'CraftedSpecially' 
        cluster-name: 'aks'
    
    - uses: azure/setup-helm@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
      id: install-helm
    
    - name: Add Chaos Mesh repo
      run: helm repo add chaos-mesh https://charts.chaos-mesh.org

    - name: Install Chaos Mesh
      run: helm install chaos-mesh chaos-mesh/chaos-mesh -n=chaos-testing --set chaosDaemon.runtime=containerd --set chaosDaemon.socketPath=/run/containerd/containerd.sock --version 2.5.1
