on: [
  workflow_dispatch
]
name: CraftedSpecially infrastructure deployment
jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: Deploy bicep to Azure
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az config set bicep.use_binary_from_path=False
          az deployment sub create \
          --location westeurope \
          --template-file ./Infrastructure/CraftedSpecially.bicep \

  deploy-aks-setup:
    needs: deploy-infrastructure
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: 'CraftedSpecially'
          cluster-name: 'aks'
      
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy to AKS
        id: deploy
        uses: Azure/K8s-deploy@v4
        with:
          namespace: 'default'
          manifests: |
            ./Infrastructure/application-infrastructure/aks-setup/namespaces.yml

      - name: 'Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'chaos-mesh'
          namespace: 'chaos-mesh'
          chart: 'chaos-mesh'
          token: '${{ github.token }}'
