name: Run stryker CI/CD
run-name: ${{ github.actor }} is killing some mutants 👽👾🧌

on: 
  workflow_dispatch:

jobs:
  mutation-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Stryker.NET
        uses: tom171296/run-stryker-net@v0.0.2
        with:
          testProject: "BusinessLogic.Test/" # required
          breakAt: "75" # Optional

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: html-report
          path: ${{github.workspace}}/BusinessLogic.Test/StrykerOutput/**/**/*.html